"""Replay real earthquakes and run USGS scenarios through the planner.

    uv run backtests/run.py

Writes backtests/RESULTS.md: the inputs used, a scorecard, a scenario table,
and one section per event with what the model saw, the plan, what actually
happened and the sources. Event definitions live in backtests/events.py.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from airlift.airbridge import build_plan  # noqa: E402
from airlift.airports import load_airports, provenance  # noqa: E402
from airlift.geo import same_country  # noqa: E402
from airlift.population import ensure_exposure  # noqa: E402
from airlift.report import fmt_people, pct, render_text  # noqa: E402
from airlift.survivability import roman  # noqa: E402
from airlift.usgs import fetch_event  # noqa: E402
from events import EVENTS, SCENARIOS  # noqa: E402

DASHBOARD = "https://sachabidermann.github.io/airlift-planner/"


def short(airport) -> str:
    return f"{airport.ident} {airport.name}"


def main() -> int:
    airports = load_airports()
    by_ident = {ap.ident: ap for ap in airports}

    plans = {}
    for ev in EVENTS + SCENARIOS:
        event = ensure_exposure(fetch_event(ev["id"]))
        plans[ev["id"]] = (event, build_plan(event, airports))
        print(f"===== {ev['name']}")
        print(render_text(plans[ev["id"]][1]))

    md = ["# Backtests and scenarios", "",
          "Generated by `uv run backtests/run.py`. Event definitions, outcomes and sources are in `backtests/events.py`.", ""]

    # ---- inputs
    md += ["## Inputs", "",
           "OurAirports changes nightly and USGS revises ShakeMaps, so results are tied to these inputs.", "",
           "| file | downloaded | sha256 |", "|---|---|---|"]
    md += [f"| {p['file']} | {p['downloaded']} | `{p['sha256'][:16]}` |" for p in provenance()]
    md += ["", "| event | shaking | exposure |", "|---|---|---|"]
    for ev in EVENTS + SCENARIOS:
        event, _ = plans[ev["id"]]
        md.append(f"| `{ev['id']}` | {event.mmi_source} | {event.exposure.source if event.exposure else 'none'} |")
    md.append("")

    # ---- scorecard
    md += ["## Scorecard: real events", "",
           "| event | flagged as likely knocked out | what happened to airports | model gateway | relief gateway used | match |",
           "|---|---|---|---|---|---|"]
    hits = scored = 0
    for ev in EVENTS:
        _, plan = plans[ev["id"]]
        flagged = ", ".join(f"{t.airport.ident} ({pct(t.usability)})" for t in plan.traps) or "none"
        gw = short(plan.gateway.field.airport) if plan.gateway else "none"
        if ev["hub_used"]:
            scored += 1
            ok = bool(plan.gateway) and plan.gateway.field.airport.ident in ev["hub_used"]
            hits += ok
            match = "yes" if ok else "no"
        else:
            match = "n/a"
        md.append(f"| {ev['name']} | {flagged} | {ev['closed']} | {gw} | {ev['hub_text']} | {match} |")
    md += ["", f"Gateway matches in {hits} of the {scored} events where a relief gateway was used. "
           "Events with no relief airlift are not scored on gateway choice.", ""]

    # ---- scenarios
    md += ["## Scenario summary", "",
           "| scenario | people at MMI VIII+ | gateway | flagged as likely knocked out | airlift capacity | share of need |",
           "|---|---:|---|---:|---:|---:|"]
    for ev in SCENARIOS:
        _, plan = plans[ev["id"]]
        gw = short(plan.gateway.field.airport) if plan.gateway else "none"
        need = "n/a" if plan.coverage is None else ("exceeds need" if plan.coverage >= 1 else pct(plan.coverage))
        priority = fmt_people(plan.demand.priority) if plan.demand else "n/a"
        md.append(f"| {ev['name']} | {priority} | {gw} | {len(plan.traps)} | {plan.delivered_tpd:,.0f} t/day | {need} |")
    md.append("")

    # ---- per event
    for section, items in (("Real events", EVENTS), ("USGS scenarios", SCENARIOS)):
        md += [f"# {section}", ""]
        for ev in items:
            event, plan = plans[ev["id"]]
            md += [f"## {ev['name']}  (`{ev['id']}`)", ""]
            src = f"Shaking: {event.mmi_source}. Exposure: {event.exposure.source if event.exposure else 'none'}."
            md += [src + (f" PAGER alert: {event.alert}." if event.alert else ""), "",
                   "**What the model saw at the airports that mattered**", "",
                   "| airport | km to damage center | MMI | usability |", "|---|---:|:-:|---:|"]
            lookup = {f.airport.ident: f for f in plan.fields}
            for ident in ev["watch"]:
                f = lookup.get(ident)
                if f is None:
                    ap = by_ident.get(ident)
                    md.append(f"| {ident} {ap.name if ap else ''} | beyond search radius | | |")
                    continue
                md.append(f"| {short(f.airport)} | {f.dist_km:,.0f} | {roman(f.mmi)} ({f.mmi:.1f}) | {pct(f.usability)} |")
            md += ["", "**Plan**", ""]
            if plan.gateway:
                g = plan.gateway
                md.append(f"- Gateway: **{short(g.field.airport)}**, {g.field.dist_km:,.0f} km, MMI {roman(g.field.mmi)}, inflow {g.inflow_tpd:,.0f} t/day")
            else:
                md.append("- Gateway: none found")
            strips = [f for f in plan.forwards if f.sorties_per_day >= 0.5]
            if strips:
                md.append("- Forward strips: " + ", ".join(f"{short(f.field.airport)} ({f.tonnes_per_day:.0f} t/day)" for f in strips[:5])
                          + (f", and {len(strips) - 5} more" if len(strips) > 5 else ""))
            if plan.traps:
                md.append("- Flagged as likely knocked out: " + ", ".join(f"{short(t.airport)} (MMI {roman(t.mmi)}, {pct(t.usability)})" for t in plan.traps))
            for alt in plan.alternatives:
                kind = "domestic" if same_country(alt.gateway.field.airport.country, plan.country) else "foreign"
                md.append(f"- Best {kind} alternative: {short(alt.gateway.field.airport)}, capacity {alt.delivered_tpd:,.0f} t/day")
            need = ""
            if plan.coverage is not None:
                need = ", more than the estimated need" if plan.coverage >= 1 else f", {pct(plan.coverage)} of estimated need"
            md.append(f"- Airlift capacity into zone: **{plan.delivered_tpd:,.0f} t/day** (upper bound), enough for about {fmt_people(plan.people_sustained)} people{need}")
            md += ["", "**What happened**" if "hub_used" in ev else "**About this scenario**", "", ev["happened"], ""]
            if ev.get("sources"):
                md += ["Sources:", ""] + [f"- {u}" for u in ev["sources"]] + [""]
            md += [f"Dashboard: {DASHBOARD}#{ev['id']}", ""]

    out = Path(__file__).resolve().parent / "RESULTS.md"
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
