"""Replay five major earthquakes and compare the plan with what actually happened.

    uv run backtests/run.py

Writes backtests/RESULTS.md and an HTML map per event in out/.
The "what happened" notes are from public reporting at the time.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from airlift.airbridge import build_plan  # noqa: E402
from airlift.airports import load_airports  # noqa: E402
from airlift.report import render_text, write_html  # noqa: E402
from airlift.survivability import roman  # noqa: E402
from airlift.usgs import fetch_event  # noqa: E402

EVENTS = [
    {
        "id": "usp000h60h",
        "name": "Haiti 2010, M7.0",
        "watch": ["MTPP", "MDSD"],
        "happened": (
            "Port-au-Prince (MTPP) runway survived but the tower and air traffic control were lost; "
            "the US Air Force took over the field and it was saturated for days, turning aircraft away. "
            "Santo Domingo (MDSD) in the Dominican Republic became the overflow hub. "
            "The USGS never produced a PAGER product for this event, so there is no demand estimate."
        ),
    },
    {
        "id": "us20002926",
        "name": "Nepal 2015, M7.8",
        "watch": ["VNKT", "VNPK"],
        "happened": (
            "Kathmandu (VNKT) was the only international gateway and saturated immediately; heavy jets "
            "damaged the runway and aircraft over 196 t were banned. Pokhara (VNPK) and small strips "
            "served as forward fields for helicopters and light aircraft. Data caveat: the airport "
            "table is current, and Pokhara International (NP-0003) only opened in 2023."
        ),
    },
    {
        "id": "us6000jllz",
        "name": "Turkey 2023, M7.8",
        "watch": ["LTDA", "LTAF", "LTAG", "LTAJ", "LTCN"],
        "happened": (
            "Hatay (LTDA) runway fractured and closed for days. Adana (LTAF) and Incirlik air base (LTAG) "
            "became the hubs; Gaziantep (LTAJ) and Kahramanmaras (LTCN) also took relief flights. "
            "Data caveat: Cukurova (LTDB) replaced Adana Sakirpasa in 2024, so today's table offers it "
            "where 2023 planners had LTAF, 30 km away."
        ),
    },
    {
        "id": "us7000kufc",
        "name": "Morocco 2023, M6.8",
        "watch": ["GMMX"],
        "happened": (
            "Marrakech Menara (GMMX) was undamaged and became the hub. The High Atlas villages were "
            "reached by helicopter and road; fixed-wing forward strips played almost no role."
        ),
    },
    {
        "id": "us7000pn9s",
        "name": "Myanmar 2025, M7.7",
        "watch": ["VYMD", "VYNT", "VYYY"],
        "happened": (
            "Mandalay (VYMD) and Nay Pyi Taw (VYNT) control towers collapsed and both airports closed. "
            "Yangon (VYYY), about 600 km south, became the entry point for international relief. "
            "The model instead prefers a closer regional airport; real operations valued Yangon's "
            "customs, fuel and handling, which the model does not yet see. Open question: does an "
            "intact regional hub with C-17 access beat a distant international one? Nobody tested it."
        ),
    },
]


def main() -> int:
    airports = load_airports()
    by_ident = {ap.ident: ap for ap in airports}
    md = ["# Backtests", "", "Five major earthquakes replayed through the planner, compared with public "
          "reporting of what relief airlifts actually did. Generated by `uv run backtests/run.py`.", ""]

    for ev in EVENTS:
        event = fetch_event(ev["id"])
        plan = build_plan(event, airports)
        html_path = write_html(plan)
        print(f"===== {ev['name']}")
        print(render_text(plan))

        md.append(f"## {ev['name']}  (`{ev['id']}`)")
        md.append("")
        md.append(f"Shaking data: {event.mmi_source}. PAGER alert: {event.alert or 'n/a'}.")
        md.append("")
        md.append("**What the model saw at the airports that mattered**")
        md.append("")
        md.append("| airport | km to damage centre | MMI | usability |")
        md.append("|---|---:|:-:|---:|")
        lookup = {f.airport.ident: f for f in plan.fields}
        for ident in ev["watch"]:
            f = lookup.get(ident)
            if f is None:
                ap = by_ident.get(ident)
                md.append(f"| {ident} {ap.name if ap else ''} | beyond search radius | | |")
                continue
            md.append(f"| {ident} {f.airport.name} | {f.dist_km:,.0f} | {roman(f.mmi)} | {f.usability:.0%} |")
        md.append("")
        md.append("**Plan**")
        md.append("")
        if plan.gateway:
            g = plan.gateway
            md.append(f"- Gateway: **{g.field.airport.label}**, {g.field.dist_km:,.0f} km, MMI {roman(g.field.mmi)}, inflow {g.inflow_tpd:,.0f} t/day")
        else:
            md.append("- Gateway: none found")
        strips = [f for f in plan.forwards if f.sorties_per_day >= 0.5]
        if strips:
            md.append("- Forward strips: " + ", ".join(f"{f.field.airport.label} ({f.tonnes_per_day:.0f} t/day)" for f in strips[:5]))
        if plan.traps:
            md.append("- Flagged as likely knocked out: " + ", ".join(f"{t.airport.label} (MMI {roman(t.mmi)})" for t in plan.traps))
        for alt in plan.alternatives:
            kind = "foreign" if alt.gateway.field.airport.country != plan.country else "domestic"
            md.append(f"- Best {kind} alternative: {alt.gateway.field.airport.label}, {alt.delivered_tpd:,.0f} t/day")
        md.append(f"- Delivered into zone: **{plan.delivered_tpd:,.0f} t/day**, sustaining about {plan.people_sustained:,.0f} people/day"
                  + (f", {plan.coverage:.0%} of estimated need" if plan.coverage is not None else ""))
        md.append("")
        md.append("**What happened**")
        md.append("")
        md.append(ev["happened"])
        md.append("")
        md.append(f"Map: `out/{ev['id']}.html` ({html_path.name})")
        md.append("")

    out = Path(__file__).resolve().parent / "RESULTS.md"
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
