"""Check our shaking grid against USGS's own numbers.

    uv run backtests/verify_shaking.py

Two independent checks, written to backtests/VERIFICATION.md:

1. PAGER publishes the intensity it assigned to every city near a quake.
   We read our grid at the same coordinates and report the difference.
2. For one event that ships both grid formats, the legacy grid.xml parser
   is compared with the modern CoverageJSON grid at random points.

If either drifts, the survivability layer is wrong and nothing downstream
can be trusted, so this runs before any release.
"""

import json
import random
import statistics
import sys
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from airlift.usgs import ShakeGrid, _product, fetch_event  # noqa: E402

EVENTS = [
    "us7000pn9s", "us6000jllz", "us7000kufc", "us20002926",
    "ak20419010", "ci38457511", "us70006vll",
    "nm19fema_m7p7_mt_se", "wa22sfz01_se",
]


def pager_cities(qid: str) -> list[dict]:
    detail = json.load(open(Path("data/usgs") / qid / "detail.json"))
    if detail.get("type") == "FeatureCollection":
        detail = detail["features"][0]
    pager = _product(detail["properties"]["products"], "losspager", "losspager-scenario")
    if pager is None:
        return []
    contents = pager["contents"]
    if "json/cities.json" in contents:
        data = requests.get(contents["json/cities.json"]["url"], timeout=60).json()
        return [{"name": c["name"], "lat": c["lat"], "lon": c["lon"], "mmi": c["mmi"], "pop": c.get("pop", 0)} for c in data["all_cities"]]
    if "pager.xml" in contents:
        import xml.etree.ElementTree as ET
        root = ET.fromstring(open(Path("data/usgs") / qid / "pager.xml").read())
        return [{"name": el.get("name"), "lat": float(el.get("lat")), "lon": float(el.get("lon")),
                 "mmi": float(el.get("mmi")), "pop": int(el.get("population") or 0)} for el in root.iter("city")]
    return []


def main() -> int:
    md = ["# Shaking verification", "",
          "Our intensity grid compared with the intensity USGS PAGER assigned to each city near the same "
          "earthquake (cities at MMI IV or more). Differences are ours minus USGS. Generated by "
          "`uv run backtests/verify_shaking.py`.", "",
          "| event | cities | mean diff | std dev | largest | biggest cities, ours vs USGS |",
          "|---|---:|---:|---:|---:|---|"]
    worst = 0.0
    notes = []
    for qid in EVENTS:
        ev = fetch_event(qid)
        detail = json.load(open(Path("data/usgs") / qid / "detail.json"))
        if detail.get("type") == "FeatureCollection":
            detail = detail["features"][0]
        prods = detail["properties"]["products"]
        sm_t = (_product(prods, "shakemap", "shakemap-scenario") or {}).get("updateTime", 0)
        pg_t = (_product(prods, "losspager", "losspager-scenario") or {}).get("updateTime", 0)
        if sm_t and pg_t and sm_t - pg_t > 30 * 86400 * 1000:
            notes.append(f"`{qid}`: the ShakeMap grid was revised {round((sm_t - pg_t) / 86400000)} days after PAGER ran, "
                         "so PAGER's city values come from an older version of the map.")
        cities = [c for c in pager_cities(qid) if c["mmi"] >= 4 and ev.shake.covers(c["lat"], c["lon"])]
        if not cities:
            md.append(f"| {qid} | no city list | | | | |")
            continue
        diffs = [ev.shake.mmi_at(c["lat"], c["lon"]) - c["mmi"] for c in cities]
        big = sorted(cities, key=lambda c: -c["pop"])[:3]
        bigtxt = ", ".join(f"{c['name']} {ev.shake.mmi_at(c['lat'], c['lon']):.1f} vs {c['mmi']:.1f}" for c in big)
        worst = max(worst, abs(statistics.mean(diffs)))
        md.append(f"| {ev.quake.place[:40]} (`{qid}`) | {len(diffs)} | {statistics.mean(diffs):+.2f} | "
                  f"{statistics.pstdev(diffs):.2f} | {max(abs(d) for d in diffs):.2f} | {bigtxt} |")
        print(f"{qid:26} cities={len(diffs):4} mean {statistics.mean(diffs):+.2f} sd {statistics.pstdev(diffs):.2f}")

    if notes:
        md += ["", "Version caveats:", ""] + [f"- {n}" for n in notes]

    # grid.xml parser vs covjson on an event that has both
    qid = "us7000pn9s"
    ev = fetch_event(qid)
    detail = json.load(open(Path("data/usgs") / qid / "detail.json"))
    sm = _product(detail["properties"]["products"], "shakemap")["contents"]
    dest = Path("data/usgs") / qid / "grid.xml"
    if not dest.exists():
        dest.write_bytes(requests.get(sm["download/grid.xml"]["url"], timeout=600).content)
    gx = ShakeGrid.from_grid_xml(dest.read_bytes())
    random.seed(1)
    pts = [(random.uniform(ev.shake.y0, ev.shake.y1), random.uniform(ev.shake.x0, ev.shake.x1)) for _ in range(500)]
    d = [gx.mmi_at(a, b) - ev.shake.mmi_at(a, b) for a, b in pts]
    md += ["", "## Legacy grid parser", "",
           f"Myanmar 2025 read through the legacy `grid.xml` parser ({gx.nx}x{gx.ny}) versus the modern CoverageJSON grid "
           f"({ev.shake.nx}x{ev.shake.ny}), 500 random points: mean difference {statistics.mean(d):+.3f}, "
           f"largest {max(abs(x) for x in d):.2f}. The legacy parser is what reads the HayWired, ShakeOut, Cascadia and "
           "Loma Prieta grids.", ""]
    print(f"grid.xml vs covjson: mean {statistics.mean(d):+.3f} max {max(abs(x) for x in d):.2f}")

    out = Path(__file__).resolve().parent / "VERIFICATION.md"
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {out}; worst mean bias {worst:.2f}")
    return 0 if worst < 0.5 else 1


if __name__ == "__main__":
    sys.exit(main())
