"""Check the shaking layer against USGS's own numbers.

    uv run backtests/verify_shaking.py

Writes backtests/VERIFICATION.md with four checks:

1. Grid vs PAGER cities. PAGER publishes the intensity it assigned to each
   city near a quake. We read our grid at the same coordinates and compare.
2. Legacy parser. For an event that ships both formats, the grid.xml parser
   is compared with the CoverageJSON grid at random points.
3. Fallback formula. When no ShakeMap exists the planner uses a distance
   formula. Its error is measured against the ShakeMap at every airport
   inside the grid of each real event.
4. Census reconstruction vs PAGER. The population method used for scenarios
   is run on US events that have real PAGER counts, and compared.

Checks 1 and 2 test that the grid is read correctly. They say nothing about
whether ShakeMap itself is right. Run this after any change to airlift/usgs.py
or airlift/population.py.
"""

import json
import random
import statistics
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from airlift.airports import load_airports  # noqa: E402
from airlift.geo import distance_km  # noqa: E402
from airlift.population import exposure_from_grid  # noqa: E402
from airlift.usgs import CACHE_DIR, ShakeGrid, _cached_get, _product, estimate_mmi, fetch_event  # noqa: E402
from events import EVENTS, SCENARIOS  # noqa: E402


def detail_of(qid: str) -> dict:
    detail = json.loads((CACHE_DIR / qid / "detail.json").read_text())
    return detail["features"][0] if detail.get("type") == "FeatureCollection" else detail


def pager_cities(qid: str) -> list[dict]:
    pager = _product(detail_of(qid)["properties"]["products"], "losspager", "losspager-scenario")
    if pager is None:
        return []
    contents = pager["contents"]
    if "json/cities.json" in contents:
        data = json.loads(_cached_get(contents["json/cities.json"]["url"], CACHE_DIR / qid / "cities.json"))
        return [{"name": c["name"], "lat": c["lat"], "lon": c["lon"], "mmi": c["mmi"], "pop": c.get("pop", 0)} for c in data["all_cities"]]
    if "pager.xml" in contents:
        root = ET.fromstring((CACHE_DIR / qid / "pager.xml").read_text())
        return [{"name": el.get("name"), "lat": float(el.get("lat")), "lon": float(el.get("lon")),
                 "mmi": float(el.get("mmi")), "pop": int(el.get("population") or 0)} for el in root.iter("city")]
    return []


def main() -> int:
    md = ["# Shaking verification", "", "Generated by `uv run backtests/verify_shaking.py`.", "",
          "## 1. Grid vs USGS PAGER city intensities", "",
          "Our grid read at each city PAGER lists (cities at MMI IV or above, inside the grid), minus the intensity "
          "PAGER assigned. Events without a PAGER city list are skipped.", "",
          "| event | cities | mean diff | mean abs diff | std dev | largest | biggest cities, ours vs USGS |",
          "|---|---:|---:|---:|---:|---:|---|"]
    events = {}
    total_cities, worst_bias, notes, legacy = 0, 0.0, [], []
    for meta in EVENTS + SCENARIOS:
        qid = meta["id"]
        ev = events[qid] = fetch_event(qid)
        if ev.shake_format == "grid.xml":
            legacy.append(meta["name"].split(",")[0])
        if ev.shake is None:
            continue
        cities = [c for c in pager_cities(qid) if c["mmi"] >= 4 and ev.shake.covers(c["lat"], c["lon"])]
        if not cities:
            continue
        prods = detail_of(qid)["properties"]["products"]
        sm_t = (_product(prods, "shakemap", "shakemap-scenario") or {}).get("updateTime", 0)
        pg_t = (_product(prods, "losspager", "losspager-scenario") or {}).get("updateTime", 0)
        if sm_t and pg_t and sm_t - pg_t > 30 * 86400 * 1000:
            notes.append(f"`{qid}`: ShakeMap revised {round((sm_t - pg_t) / 86400000)} days after PAGER ran.")
        diffs = [ev.shake.mmi_at(c["lat"], c["lon"]) - c["mmi"] for c in cities]
        big = sorted(cities, key=lambda c: -c["pop"])[:3]
        bigtxt = ", ".join(f"{c['name']} {ev.shake.mmi_at(c['lat'], c['lon']):.1f} vs {c['mmi']:.1f}" for c in big)
        mean = statistics.mean(diffs)
        total_cities += len(diffs)
        worst_bias = max(worst_bias, abs(mean))
        md.append(f"| {meta['name']} | {len(diffs)} | {mean:+.2f} | {statistics.mean(abs(d) for d in diffs):.2f} | "
                  f"{statistics.pstdev(diffs):.2f} | {max(abs(d) for d in diffs):.2f} | {bigtxt} |")
        print(f"{qid:28} cities={len(diffs):4} mean {mean:+.2f}")
    md += ["", f"Total cities compared: {total_cities:,}.", ""]
    if notes:
        md += ["For these events the ShakeMap was revised after PAGER ran, so PAGER's city values come from an older "
               "map. This is a likely cause of part of the differences above, not a proven one.", ""] + [f"- {n}" for n in notes] + [""]

    # ---- 2. legacy parser
    qid = "us7000pn9s"
    ev = events[qid]
    sm = _product(detail_of(qid)["properties"]["products"], "shakemap")["contents"]
    gx = ShakeGrid.from_grid_xml(_cached_get(sm["download/grid.xml"]["url"], CACHE_DIR / qid / "grid.xml"))
    rng = random.Random(1)
    pts = [(rng.uniform(ev.shake.y0, ev.shake.y1), rng.uniform(ev.shake.x0, ev.shake.x1)) for _ in range(500)]
    d = [gx.mmi_at(a, b) - ev.shake.mmi_at(a, b) for a, b in pts]
    md += ["## 2. Legacy grid.xml parser vs CoverageJSON", "",
           f"Myanmar 2025 read through both ({gx.nx}x{gx.ny} vs {ev.shake.nx}x{ev.shake.ny} cells), 500 random points: "
           f"mean difference {statistics.mean(d):+.3f}, mean absolute {statistics.mean(abs(x) for x in d):.3f}, "
           f"largest {max(abs(x) for x in d):.2f}.", "",
           "Events that use the legacy parser because USGS ships no CoverageJSON for them: " + ", ".join(legacy) + ".", ""]
    print(f"legacy parser: mean {statistics.mean(d):+.3f} max {max(abs(x) for x in d):.2f}")

    # ---- 3. fallback formula
    airports = load_airports()
    md += ["## 3. Fallback distance formula vs ShakeMap", "",
           "`estimate_mmi` (Allen, Wald and Worden 2012) compared with the ShakeMap at every airport inside the grid "
           "of each real event. This is the error to expect in the first minutes, before USGS publishes a ShakeMap.", "",
           "| event | airports | mean abs error | bias | mean abs error where MMI >= 5 |", "|---|---:|---:|---:|---:|"]
    pooled, pooled5 = [], []
    for meta in EVENTS:
        ev = events[meta["id"]]
        q = ev.quake
        errs, errs5 = [], []
        for ap in airports:
            if not ev.shake.covers(ap.lat, ap.lon):
                continue
            real = ev.shake.mmi_at(ap.lat, ap.lon)
            est = estimate_mmi(q.magnitude, q.depth_km, distance_km(q.lat, q.lon, ap.lat, ap.lon))
            errs.append(est - real)
            if real >= 5:
                errs5.append(est - real)
        pooled += errs
        pooled5 += errs5
        md.append(f"| {meta['name']} | {len(errs)} | {statistics.mean(abs(e) for e in errs):.2f} | {statistics.mean(errs):+.2f} | "
                  + (f"{statistics.mean(abs(e) for e in errs5):.2f}" if errs5 else "n/a") + " |")
    md += [f"| **all events pooled** | {len(pooled)} | {statistics.mean(abs(e) for e in pooled):.2f} | {statistics.mean(pooled):+.2f} | "
           f"{statistics.mean(abs(e) for e in pooled5):.2f} |", ""]
    print(f"fallback formula: pooled mean abs error {statistics.mean(abs(e) for e in pooled):.2f}")

    # ---- 4. Census reconstruction vs PAGER
    md += ["## 4. Census population reconstruction vs USGS PAGER", "",
           "Scenarios without PAGER get their exposure from `airlift/population.py`. Here that reconstruction is run "
           "on US events that do have PAGER, and compared. A ratio of 1.00 is perfect agreement. Small counts are "
           "unreliable: a few thousand people can sit on either side of an intensity boundary.", "",
           "| event | PAGER MMI VII+ | ours | ratio | PAGER MMI VIII+ | ours | ratio |", "|---|---:|---:|---:|---:|---:|---:|"]
    for meta in EVENTS + SCENARIOS:
        ev = events[meta["id"]]
        if ev.exposure is None or ev.shake is None or ev.exposure.main_country(valid={"US", "PR"}) is None:
            continue
        ours = exposure_from_grid(ev.shake)
        cells = []
        for level in (7, 8):
            real, mine = ev.exposure.at_least(level), ours.at_least(level)
            cells += [f"{real:,}", f"{mine:,}", f"{mine / real:.2f}" if real else "n/a"]
        md.append(f"| {meta['name']} | " + " | ".join(cells) + " |")
        print(f"pager vs census {meta['id']:26} VIII+ {cells[3]} vs {cells[4]}")
    md.append("")

    out = Path(__file__).resolve().parent / "VERIFICATION.md"
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {out}; worst mean bias vs PAGER {worst_bias:.2f}")
    return 0 if worst_bias < 0.5 else 1


if __name__ == "__main__":
    sys.exit(main())
